services:
  mongo:
    image: mongo:latest
    container_name: gs-mongo
    ports:
      - "28017:27017"
    volumes:
      - sbmo_mongo_db:/data/db
      - sbmo_mongo_configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

networks:
  sbmo:
    driver: 'bridge'

volumes:
  sbmo_mongo_db:
  sbmo_mongo_configdb: